clean: Simplify sh scripts
Simpler to have some that must be sourced (utilities) and others than
must be run.
Rather than hybrid ones that can be run and sourced. At some point, you
gotta be pragmatic.

diff --git a/.scripts/create-github-release b/.scripts/create-github-release
--- a/.scripts/create-github-release
+++ b/.scripts/create-github-release
@@ -1,14 +1,11 @@
 #!/bin/sh
-alias _is_run='!(return 0 2>/dev/null)'
+(return 0 2>/dev/null) && {
+    echo "ERROR: This script cannot be sourced. It must be run." >&2
+    return 1
+}
 
-if _is_run; then
-    SCRIPTS_DIR=$(dirname "$(realpath "$0")")
-else
-    if [ -z "${SCRIPTS_DIR:-}" ]; then
-        echo "ERROR: If sourced and not run, SCRIPTS_DIR env var must contain the path to scripts directory" >&2
-        return 1  # sourced
-    fi
-fi
+SCRIPTS_DIR=$(dirname "$(realpath "$0")")
+ROOT_DIR=$(realpath "$SCRIPTS_DIR/..")
 
 . "$SCRIPTS_DIR/common/logs.sh"
 
@@ -67,6 +64,4 @@ function create_github_release()
 }
 
 
-if _is_run; then
-    create_github_release "$@"
-fi
+create_github_release "$@"
diff --git a/.scripts/fetch_links b/.scripts/fetch_links
--- a/.scripts/fetch_links
+++ b/.scripts/fetch_links
@@ -1,6 +1,11 @@
 #!/bin/sh
-ROOT_DIR=$(realpath $(dirname "$0")/..)
-cd "$ROOT_DIR" || exit 1
+(return 0 2>/dev/null) && {
+    echo "ERROR: This script cannot be sourced. It must be run." >&2
+    return 1
+}
+
+SCRIPTS_DIR=$(dirname "$(realpath "$0")")
+ROOT_DIR=$(realpath $SCRIPTS_DIR/..)
 
 
 function _fetch_link()
@@ -78,7 +83,6 @@ function fetch_links()
     done
     unset line
 }
-
 
 
 fetch_links "$@"
diff --git a/.scripts/for-each-component b/.scripts/for-each-component
--- a/.scripts/for-each-component
+++ b/.scripts/for-each-component
@@ -1,15 +1,10 @@
 #!/bin/sh
-alias _is_run='!(return 0 2>/dev/null)'
+(return 0 2>/dev/null) && {
+    echo "ERROR: This script cannot be sourced. It must be run." >&2
+    return 1
+}
 
-if _is_run; then
-    SCRIPTS_DIR=$(dirname "$(realpath "$0")")
-else
-    if [ -z "${SCRIPTS_DIR:-}" ]; then
-        echo "ERROR: If sourced and not run, SCRIPTS_DIR env var must contain the path to scripts directory" >&2
-        return 1  # sourced
-    fi
-fi
-
+SCRIPTS_DIR=$(dirname "$(realpath "$0")")
 ROOT_DIR=$(realpath "$SCRIPTS_DIR/..")
 
 
@@ -28,6 +23,5 @@ function for_each_component()
     done
 }
 
-if _is_run; then
-    for_each_component "$@"
-fi
+
+for_each_component "$@"
