fix: pimp sh .scripts & overwrite release if pushing same version

diff --git a/.scripts/publish b/.scripts/publish
--- a/.scripts/publish
+++ b/.scripts/publish
@@ -1,27 +1,36 @@
 #!/bin/sh
-if ( return 0 2>/dev/null ); then
-    echo "[ERROR] This script must be run, not sourced." >&2
-    return 1
+alias _is_run='!(return 0 2>/dev/null)'
+
+if _is_run; then
+    SCRIPTS_DIR=$(dirname "$(realpath "$0")")
+else
+    if [ -z "${SCRIPTS_DIR:-}" ]; then
+        echo "ERROR: If sourced and not run, SCRIPTS_DIR env var must contain the path to scripts directory" >&2
+        return 1  # sourced
+    fi
 fi
 
-SCRIPTS_DIR=$(dirname "$(realpath "$0")")
 ROOT_DIR=$(realpath "$SCRIPTS_DIR/..")
 
+. "$SCRIPTS_DIR/common/logs.sh"
 . "$SCRIPTS_DIR/common/utils.sh"
+. "$SCRIPTS_DIR/create-github-release"
 
 
-# -- Constants
+# == Constants
 TARGET_REPOSITORY="pahowlo/pahowlo.github.io"
 TARGET_BRANCH="main"
 
-# -- Function
+
+# == Main function
 # Publish the built application to the target repository
 function publish()
 {
+    local shell_options=$(set +o); set +e
     (
-        set -euo pipefail
+        set -eu
 
-        # Verification
+        # Build if build was not found
         if [ -z "$(ls -A "$ROOT_DIR/target" 2>/dev/null)" ]; then
             pnpm install:all
             pnpm build:all
@@ -33,6 +42,7 @@ function publish()
 
         mkdir -p "$ROOT_DIR/tmp"
         local temp_dir=$(mktemp -d -p "$ROOT_DIR/tmp" "publish-XXXXXXXX")
+        echo "TEMP_DIR       = $temp_dir"
         trap 'rm -rf "$temp_dir"' EXIT
 
         echo "VERSION_NUMBER = $version_number"
@@ -49,7 +59,8 @@ function publish()
         # Copy new files to the target repository
         cp -r "$ROOT_DIR/target/." ./
 
-        find . -mindepth 1 -maxdepth 5 ! -path './.git*' | sort | cut -c3-
+        echo
+        find . -mindepth 1 -maxdepth 5 ! -path './.git*' | cut -c3- | sort
         echo
 
         git add -A
@@ -63,6 +74,7 @@ function publish()
         # Create tag from source repository
         cd $ROOT_DIR
         create_github_release "v$version_number"
+        echo $?
 
         # Commit and push changes
         cd "$temp_dir"
@@ -75,53 +87,19 @@ function publish()
             commit_args+=" -m \"$new_commit_msg\""
         fi
         git commit $commit_args
-        git push
-    ) || {
-        echo "[ERROR] Failed to publish to $TARGET_REPOSITORY" >&2
-        return 1
-    }
-}
+        git push --force-with-lease
+    )
+    exit_code=$?
+    eval "$shell_options"
 
-function create_github_release()
-{
-
-    local version="${1:-}"
-    local message="${2:-}"
-
-    if [ -z "$version" ]; then
-        echo "[ERROR] Version argument is required to create GitHub tag." >&2
+    if [ "$exit_code" -ne 0 ]; then
+        log_error "Failed to publish to $TARGET_REPOSITORY" >&2
         return 1
     fi
-    (
-        set -euo pipefail
-
-        local release_create_args=
-        if [ ! -z "$message" ]; then
-            release_create_args+=" --notes \"$message\""
-        fi
-
-        local github_repository=$(git config --get remote.origin.url | sed -E "s~.*[:/]([^/:]+)/([^/]+)[.]git$~\1/\2~g" )
-        echo "$github_repository"
-
-        # Delete existing tag if any of the same version
-        git tag -d               "$version" 2>/dev/null || true
-        git push origin --delete "$version" 2>/dev/null || true
-
-        # Create and push new tag
-        git tag -s "$version" -m ""
-        git push origin "$version"
-
-        # Create a release on GitHub
-        gh release create "$version" --title "$version" $release_create_args --repo "$github_repository"
-
-    ) || {
-        echo "[ERROR] Failed to create tag $version with message:" >&2
-        echo "$message" >&2 d
-        echo
-        return 1
-    }
+    return 0
 }
 
 
-
-publish "$@"
+if _is_run; then
+    publish "$@"
+fi
